### ISSUE TITLE
How do I find the names of all the panels and charaters?

### ISSUE THREAD

**Issue by SuperSonicJyt** [plokmijnuhby/StorytellerCustomLevels#1]
I wanted to use Hatey in one of my custom levels but I did not know the name for him and the game said Hatey was an invalid input. Could you please give me a list of all the charater and panel names in the game files or put it on the github page. Thank you for making this mod I wanted it for so long.

**Comment by plokmijnuhby** [comment]
I assume you figured this out, but they are in [enums](https://github.com/plokmijnuhby/StorytellerCustomLevels/tree/master/enums). Hatey is called `DwarfHatey`.
